# Generated by Django 3.1.5 on 2021-01-14 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('last_activity', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('distance', models.DecimalField(decimal_places=1, default=0, max_digits=200)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stravaleaderboard.club')),
            ],
        ),
    ]
