# Generated by Django 3.1.5 on 2021-01-14 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0002_club_distances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='last_activity',
            field=models.JSONField(default={}),
        ),
        migrations.CreateModel(
            name='total_distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stravaleaderboard.distances')),
            ],
        ),
    ]
