# Generated by Django 3.1.5 on 2021-01-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0005_club_total_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='last_activity',
        ),
        migrations.AddField(
            model_name='club',
            name='clubid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=0),
        ),
    ]
