# Generated by Django 3.1.5 on 2021-01-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0006_auto_20210114_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='clubid',
            new_name='club_id',
        ),
    ]
