# Generated by Django 3.1.5 on 2021-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0007_auto_20210114_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.TextField(max_length=15),
        ),
    ]
