# Generated by Django 3.1.5 on 2021-01-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0009_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='name',
            field=models.TextField(default='aa', max_length=200),
        ),
    ]
