# Generated by Django 3.1.5 on 2021-01-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0010_secret_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1610582401),
        ),
    ]
