# Generated by Django 3.1.5 on 2021-01-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0011_auto_20210114_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1610323200),
        ),
    ]
