# Generated by Django 3.1.5 on 2021-01-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0012_auto_20210115_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1610323201),
        ),
    ]
