# Generated by Django 3.1.5 on 2021-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0015_club_currentpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='currentpoints',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
    ]
