# Generated by Django 3.1.5 on 2021-01-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0016_auto_20210121_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distances',
            name='points',
        ),
        migrations.AddField(
            model_name='distances',
            name='currentpoints',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
    ]
