# Generated by Django 3.1.5 on 2021-01-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0017_auto_20210121_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distances',
            old_name='currentpoints',
            new_name='points',
        ),
    ]
