# Generated by Django 3.2.7 on 2021-10-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0018_auto_20210121_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='percentage',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1615158000),
        ),
    ]
