# Generated by Django 4.0.1 on 2022-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0019_alter_club_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1615158001),
        ),
    ]
