# Generated by Django 3.2.7 on 2021-10-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0019_auto_20211004_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
