# Generated by Django 4.0.1 on 2022-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0020_alter_club_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1615158000),
        ),
    ]
