# Generated by Django 3.2.7 on 2021-10-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0020_delete_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='currentdistance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
        migrations.AddField(
            model_name='club',
            name='total_points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1633039201),
        ),
    ]
