# Generated by Django 4.0.1 on 2022-02-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0022_remove_club_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='distances',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
