# Generated by Django 4.0.1 on 2022-02-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0023_distances_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='distances',
            name='pre_update_distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=200),
        ),
    ]
