# Generated by Django 4.0.1 on 2022-02-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0024_distances_pre_update_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distances',
            name='pre_update_distance',
        ),
        migrations.RemoveField(
            model_name='distances',
            name='updated',
        ),
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1644793200),
        ),
    ]
