# Generated by Django 4.0.1 on 2022-02-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0025_remove_distances_pre_update_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1644796801),
        ),
    ]
