# Generated by Django 4.0.1 on 2022-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaleaderboard', '0026_alter_club_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='totalPoints',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='last_update',
            field=models.IntegerField(default=1644796800),
        ),
    ]
